name: just_in_play_proof
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  flutter_riverpod: ^2.4.4
  equatable: ^2.0.5
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.12.0
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.8
  flutter_secure_storage: ^9.0.0
  go_router: ^12.0.0
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/app_icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/just_play_logo.jpeg"
  min_sdk_android: 21



